### PR TITLE
[BUG] Remove https in Local Environment Logs

### LINKED ISSUE #88: [BUG] remove https in email links when in local environment
locally there are no emails being sent, the links are just printed out in the console. We can use the if s.cfg.Env == "dev" check to remove https on local domains when printing in console

### PR DESCRIPTION
**Pull request by Vasanth-Korada**
/claim #88

Fixes #88

@dm161 

1. Removed https:// in local when the environment is DEV
2. Added UrlProtocol Variable in config.go
3. If ENV !="DEV" then UrlProtocol will have https:// else empty string
4. Replaced all occurrences of https:// with UrlProtocol variable from Config

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -246,6 +247,10 @@ func LoadConfig() (Config, error) {
 	if isLocal != "" {
 		isLocalBool = true
 	}
+	var urlProtocol string
+	if env != "dev" {
```
Comment (dm161) [inline internal/config/config.go:251]:
```suggestion
	if strings.EqualFold(env, "dev") {
```

File: internal/config/config.go [hunk 2]
```diff
@@ -59,6 +59,7 @@ type Config struct {
 	DevelopersBannerLink     string
 	DevelopersBannerText     string
 	IsLocal                  bool
+	UrlProtocol              string
```
Comment (dm161) [inline internal/config/config.go:62]: can you please rename UrlProtocol to URLProtocol everywhere to keep with current naming conventions?

File: internal/config/config.go [hunk 3]
```diff
@@ -246,6 +247,10 @@ func LoadConfig() (Config, error) {
 	if isLocal != "" {
 		isLocalBool = true
 	}
+	var urlProtocol string
```
Comment (dm161) [inline internal/config/config.go:250]:
```suggestion
	urlProtocol = "http://"
```

**Comment by dm161** [comment]
thank you @Vasanth-Korada
