### PR TITLE
[Bug Fix] Redirect logged users when visiting "join community" page

### LINKED ISSUE #89: [BUG] redirect logged users when visiting "join community" pages
- admins, recruiters, developers when logged in should be redirected to the developers page when they visit the /Join-Golang-Community or /Hire-From-Golang-Community pages
- test locally
- add redirect to handlers

### PR DESCRIPTION
**Pull request by Vasanth-Korada**
/claim #89

Fixes #89 

@dm161 

1. Logged In users are redirected to /Golang-Developers when they visit /Join-Golang-Community or /Hire-From-Golang-Community pages
2. Added Conditional Redirect in the handlers

### CODE REVIEW

File: internal/handler/handlers.go [hunk 1]
```diff
@@ -1630,7 +1642,13 @@ func IndexPageHandler(svr server.Server, jobRepo *job.Repository) http.HandlerFu
 
 func PermanentRedirectHandler(svr server.Server, dst string) http.HandlerFunc {
 	return func(w http.ResponseWriter, r *http.Request) {
-		svr.Redirect(w, r, http.StatusMovedPermanently, fmt.Sprintf("%s%s/%s", svr.GetConfig().URLProtocol, svr.GetConfig().SiteHost, dst))
+		profile, _ := middleware.GetUserFromJWT(r, svr.SessionStore, svr.GetJWTSigningKey())
```
Comment (dm161) [inline internal/handler/handlers.go:1645]: any reason why you changed this function? changing the other handlers would be enough unless i am missing something?

File: internal/handler/handlers.go [hunk 2]
```diff
@@ -96,13 +96,25 @@ func DevelopersHandler(svr server.Server, devRepo *developer.Repository) http.Ha
...
 	}
 }
 
 func SubmitRecruiterProfileHandler(svr server.Server, devRepo *developer.Repository) http.HandlerFunc {
 	return func(w http.ResponseWriter, r *http.Request) {
-		svr.RenderPageForProfileRegistration(w, r, devRepo, "submit-recruiter-profile.html")
+		profile, _ := middleware.GetUserFromJWT(r, svr.SessionStore, svr.GetJWTSigningKey())
+		if profile != nil {
+			routeName := fmt.Sprintf("%s-Developers", strings.Title(svr.GetConfig().SiteJobCategory))
+			svr.Redirect(w, r, http.StatusMovedPermanently, fmt.Sprintf("https://%s/%s", svr.GetConfig().SiteHost, routeName))
```
Comment (dm161) [inline internal/handler/handlers.go:114]: can you please remove the else and return early here? to avoid unnecessary nesting
also please use URLProtocol if you can and don't hardcode https

Comment (dm161) [reply internal/handler/handlers.go:114]: same for line 102

**Comment by Vasanth-Korada** [comment]
@dm161 fixed the PR comments and pushed

**Comment by dm161** [comment]
sorry @Vasanth-Korada i missed this is it possible to open a PR with {{ if not .LoggedUser }}display button{{ end }} so that we dont show the button also for logged users?
image

**Comment by Vasanth-Korada** [comment]
Ok @dm161 will raise a PR
